theme: jekyll-theme-minimal
title: Kaleb Worku
description: My name is Kaleb Worku, and I am an aspiring cybersecurity professional with research interests in the historical development of cyber policy, industrial control systems, and public-sector cybersecurity. I am pursuing my master's in cybersecurity management and technology at Augusta University. I enjoy running and weightlifting. Bookmark this to keep an eye on my cyber history project updates!
